sonar.sources=app,deployment
# exclude test files from analysis
sonar.exclusions=**/*_test.go,**/docs/**,**/test/**,**/config/**,**/include/**,**/generated/**,**/*_generated.go,**/extra/**,**/wire_gen.go,**/tools/**
sonar.cpd.exclusions=**/include/**,**/*_generated.go,**/cmd/**,**/testdata/**,**/tools/**,**/graph/**,**/*.html
sonar.coverage.exclusions=**/include/**,**/*_generated.go,**/cmd/**,**/testdata/**,**/tools/**,**/graph/**,**/*.html
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=**/*.coverage.out
sonar.go.tests.reportPaths=test_results.out
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
